/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package org.javiervega.vista;

import org.javiervega.Modelo.Restaurante1;
import org.javiervega.Controlador.ControlDeRestaurante1;
/**
 *
 * @author santiago
 */
public class VistaAgregaPlatillo extends javax.swing.JInternalFrame {

    public ControlDeRestaurante1 controlador = ControlDeRestaurante1.getInstancia();
    /**
     * Creates new form VistaAgregarComida
     */
    public VistaAgregaPlatillo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDeEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblIngresePlatillo = new javax.swing.JLabel();
        txtIngresePlatillo = new javax.swing.JTextField();
        lblIdPlatillo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdPlatillo = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        botonGuardarPlatillo = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("Añadir Platillo Al Menu.  😋");

        lblIngresePlatillo.setText("Ingrese El Nombre Del Platillo Que Desea Agregar");

        lblIdPlatillo.setText("Ingrese El ID Del Platillo.");

        jLabel3.setText("Recuerde, No Puede Ser Un ID Repetido.");

        botonGuardarPlatillo.setText("Guardar Platillo  👍");
        botonGuardarPlatillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarPlatilloActionPerformed(evt);
            }
        });

        panelDeEscritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(lblIngresePlatillo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(txtIngresePlatillo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(lblIdPlatillo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(txtIdPlatillo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        panelDeEscritorio.setLayer(botonGuardarPlatillo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout panelDeEscritorioLayout = new javax.swing.GroupLayout(panelDeEscritorio);
        panelDeEscritorio.setLayout(panelDeEscritorioLayout);
        panelDeEscritorioLayout.setHorizontalGroup(
            panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeEscritorioLayout.createSequentialGroup()
                .addGroup(panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeEscritorioLayout.createSequentialGroup()
                        .addGroup(panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDeEscritorioLayout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDeEscritorioLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIngresePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIngresePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(panelDeEscritorioLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(botonGuardarPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeEscritorioLayout.setVerticalGroup(
            panelDeEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeEscritorioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblIngresePlatillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIngresePlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblIdPlatillo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtIdPlatillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(botonGuardarPlatillo)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDeEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarPlatilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarPlatilloActionPerformed
        // TODO add your handling code here:
        Restaurante1 platillo =new Restaurante1();
        platillo.setIdPlatillo(Integer.parseInt(txtIdPlatillo.getText()));
        platillo.setNombrePlatillo(txtIngresePlatillo.getText());
        controlador.agregarPlatillo(platillo);
        this.setVisible(false);
        txtIdPlatillo.setText("");
        txtIngresePlatillo.setText("");
    }//GEN-LAST:event_botonGuardarPlatilloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardarPlatillo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIdPlatillo;
    private javax.swing.JLabel lblIngresePlatillo;
    private javax.swing.JDesktopPane panelDeEscritorio;
    private javax.swing.JTextField txtIdPlatillo;
    private javax.swing.JTextField txtIngresePlatillo;
    // End of variables declaration//GEN-END:variables
}
